[zokrates]
BIN_PATH = "/Users/dc/research_project/ZoKrates/target/release/zokrates"
STDLIB_PATH = "/Users/dc/research_project/ZoKrates/zokrates_stdlib/stdlib"

[context]
    ROOT_DIR = "/Users/dc/research_project/zk_relay_poc/zk_relay/data/"
    [context.code]
    CODE_DIR = "code/"
    CODE_FILE_NAME = "validate_batch7.zok"
    [context.program]
    PROGRAM_DIR = "zok_program/"
    PROGRAM_FILE_NAME = "test"
    ABI_FILE_NAME = "abi.json"
    [context.setup]
    SETUP_DIR = "setup/"
    VKEY_FILE_NAME = "verification.key"
    PKEY_FILE_NAME = "proving.key"
    PROVING_SCHEME_NAME = "g16"
    [context.proof]
    PROOF_DIR = "proof/"
    WITNESS_FILE_NAME = "witness"
    PROOF_FILE_NAME = "proof.json"
    [context.verify]
    VERIFICATION_DIR = "verify/"
    CONTRACT_FILE_NAME = "verifier.sol"