[zokrates]
BIN_PATH = "/Users/dc/research_project/ZoKrates/target/release/zokrates"
STDLIB_PATH = "/Users/dc/research_project/ZoKrates/zokrates_stdlib/stdlib"

[context]
PROVING_SCHEME_NAME = "g16"
ROOT_DIR = "/Users/dc/github/zk_relay_poc/zk_relay/zok_src/"

[context.code]
CODE_DIR = "code/"
CODE_FILE_NAME = "validate_batch2.zok"

[context.data]
DATA_DIR = "data/batch2"
PROGRAM_FILE_NAME = "zok"
ABI_FILE_NAME = "abi.json"
VKEY_FILE_NAME = "verification.key"
PKEY_FILE_NAME = "proving.key"
WITNESS_FILE_NAME = "witness"
PROOF_FILE_NAME = "proof.json"

[context.contract]
CONTRACT_DIR = "contract/"
CONTRACT_FILE_NAME = "verifier2.sol"
